### PR TITLE
Update docs of Accordion

### PR DESCRIPTION
**Pull request by aube-dev**
## Description

The description of Accordion in documentation has explained the type of prop `data` as just `array`, and used wrong example of prop `data`. The type of prop `data` actually is:
```typescript
Array<{
  title: string;
  bodies: string[];
}>
```
The previous description could not explain enough about prop `data`, in my opinion. So I updated documentation of prop `data`, and `data` example in usage.

## Test Plan

N/A

## Related Issues

N/A

## Tests

N/A

## Checklist

Before you create this PR confirms that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide](https://github.com/dooboolab/dooboo-ui/blob/master/CONTRIBUTING.md) and followed the process outlined there for submitting PRs.
- [x] Run `yarn test:all` and make sure nothing fails. You can run `yarn test -u` to update snapshots if needed.
- [x] I am willing to follow-up on review comments in a timely manner.

### CODE REVIEW

**Comment by luke-hanwook** [comment]
Thanks PR. I agree with your opinion. 
while enhancing this component, I was organized data type definition.
I think you can refer to #108.

**Comment by aube-dev** [comment]
@luke-hanwook
Thank you for your reply! I agree and will apply your suggestion now.

**Comment by luke-hanwook** [comment]
I would like to additional work together on this PR!
I planned for [Accordion] docs.
- consistent usage
- update props
- basic accordion
- controlled animation (sholudAnamate, animDuration)
- styled accordion (style, styles)
- customization (renderTitle, renderBody, toggleElement)
- add snack
how about it?

**Comment by aube-dev** [comment]
I'd love to! What could I do more for helping this additional work?

**Comment by luke-hanwook** [comment]
> I'd love to! What could I do more for helping this additional work?

I think you combine your update commit into one and write commit msg in detail. 😃
and about collaboration I think you can refer to [tutorial](https://www.youtube.com/watch?v=tX2qn2x6v48&list=PLMu8UG37vF6rXLLV3NfxnV4MLNAIhRvvI&index=9) for `git rabase`

**Comment by luke-hanwook** [comment]
I think it would be good to refer to the documentation of other components or `git log`
And I think you can update all props refer to [Accordion] type definition for good first issue. 👍🏻

**Comment by aube-dev** [comment]
Thank you for your kind comments, but I am afraid I do not properly understand. Could you explain more detail if you don't mind?

**Comment by luke-hanwook** [comment]
> Thank you for your kind comments, but I am afraid I do not properly understand. Could you explain more detail if you don't mind?

Yes! i am ready to explain more detail to you. Could you tell me what do not you understand?
if you want to communicate in korean, let's look for other channel.

**Comment by aube-dev** [comment]
> Yes! i am ready to explain more detail to you. Could you tell me what do not you understand?
if you want to communicate in korean, let's look for other channel.

I really appreciate that! Points that I do not understand are:

> I think you combine your update commit into one and write commit msg in detail. 😃
- Does this mean I have to squash my 2 commits('Update docs of Accordion', 'Update docs of `data` of Accordion') into one commit, or is there other meaning?

> and about collaboration I think you can refer to [tutorial](https://www.youtube.com/watch?v=tX2qn2x6v48&list=PLMu8UG37vF6rXLLV3NfxnV4MLNAIhRvvI&index=9) for `git rabase`
- May I ask you what does your comment about rebase mean? I could not find reason why I have to use rebase in this case.

Even I asked questions here, I'd love to communicate also in Korean for proper understanding if you don't mind. Please let me know if there are way(channel) to contact that you feel comfortable.

**Comment by luke-hanwook** [comment]
This is a just my opinion! 😄
it's mean to squash two commit and rewrite commit message. to do that you need to `git rebase`.
I think we would better write a neat logs for reference or code review because i will add my work for collaboration.

**Comment by aube-dev** [comment]
fully understood 👍 I think I was little confused because I have not used rebase after push, to protect comments on PR. thank you! All my questions seem to be solved before contacting in Korean fortunately 🥠 but still need conversations about collaboration, so I will contact by mail in a moment and back to here when we are ready to collaborate.

**Comment by luke-hanwook** [comment]
@aube-dev 
Sorry for confusing. if you have any suggestion or feedback, please feel free to leave any comments. it's not rule and i am a contributor too like you. 😄 for more information, refer to the e-mail. thanks~

**Comment by aube-dev** [comment]
We decided to collaborate in new PR!
@hyochan Sorry to mention but our conversation is now over, so please feel free to review this PR. thank you!

**Review by hyochan — APPROVED** [review]
Would be great if we can extend this example and tell user than beyond the `text` is supported in [Accordion]!

@luke-hanwook  Thanks for the great discussion.

**Pull request merged**
